### ISSUE TITLE
Admin panel: Deleting images

### ISSUE THREAD

**Issue by Ghornos** [CosmeticeHotel/site#7]
Actual behavior: Cannot delete pictures "/Products/Geneva Guild/Geneva Guild C artridge body & hair wash di spenser - 340m l.jpg" & "/Products/Geneva Guild/GG Crtdg body & hairdispense r340ml.jpg"

Expected behavior: Should be possibility to delete images

1. Login as administrator.
2. Open admin panel.
3. Go to "Image manager"
4. Try to delete the above files.

![screenshot_65](https://user-images.githubusercontent.com/30202959/28277060-656ab6cc-6b21-11e7-9120-0e1d0b24ed7d.png)

**Comment by ghost** [comment]
Char `&` was used in filename so Opencart can't find file to delete.

Workarounds: 

- Don't use special chars in file names. Latin, numbers, minus and underscore won't cause any problems. 
- Delete files with ubuntu console
