### ISSUE TITLE
Delete files

### ISSUE THREAD

**Issue by Ghornos** [CosmeticeHotel/site#8]
Delete files: 
"/Products/Geneva Guild/Geneva Guild C artridge body & hair wash di spenser - 340m l.jpg" 
& 
"/Products/Geneva Guild/GG Crtdg body & hairdispense r340ml.jpg"

**Comment by ghost** [comment]
no such file `/Products/Geneva Guild/GG Crtdg body & hairdispense r340ml.jpg`
